// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4pEm_BN7YpMlAXSEsMI9wLOZAs7XMTFY',
    appId: '1:507807311380:web:14fab7c9fc6a46f8dfe901',
    messagingSenderId: '507807311380',
    projectId: 'find-my-spot-8783e',
    authDomain: 'find-my-spot-8783e.firebaseapp.com',
    storageBucket: 'find-my-spot-8783e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcqVLAlek5lxZE64g9rAG_D64TGVyqJ0',
    appId: '1:507807311380:android:5e9831a6ff0933e0dfe901',
    messagingSenderId: '507807311380',
    projectId: 'find-my-spot-8783e',
    storageBucket: 'find-my-spot-8783e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNsY5FM4J0xQK3txmA31_kdMhwLefouB0',
    appId: '1:507807311380:ios:2d7800069d21ab98dfe901',
    messagingSenderId: '507807311380',
    projectId: 'find-my-spot-8783e',
    storageBucket: 'find-my-spot-8783e.appspot.com',
    iosBundleId: 'com.example.inparkmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNsY5FM4J0xQK3txmA31_kdMhwLefouB0',
    appId: '1:507807311380:ios:2d7800069d21ab98dfe901',
    messagingSenderId: '507807311380',
    projectId: 'find-my-spot-8783e',
    storageBucket: 'find-my-spot-8783e.appspot.com',
    iosBundleId: 'com.example.inparkmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4pEm_BN7YpMlAXSEsMI9wLOZAs7XMTFY',
    appId: '1:507807311380:web:f97a22bafb90e160dfe901',
    messagingSenderId: '507807311380',
    projectId: 'find-my-spot-8783e',
    authDomain: 'find-my-spot-8783e.firebaseapp.com',
    storageBucket: 'find-my-spot-8783e.appspot.com',
  );
}
