// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAesx0GANv4-I5x2LtQy6MwJrHos3CjKgE',
    appId: '1:595794346344:android:72673057576730d5a916dd',
    messagingSenderId: '595794346344',
    projectId: 'inpark-5a693',
    databaseURL: 'https://inpark-5a693-default-rtdb.firebaseio.com',
    storageBucket: 'inpark-5a693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPduVCB9zGe9-ARpzsJ6TAugorPAbhbU',
    appId: '1:595794346344:ios:aab8b15649bfc247a916dd',
    messagingSenderId: '595794346344',
    projectId: 'inpark-5a693',
    databaseURL: 'https://inpark-5a693-default-rtdb.firebaseio.com',
    storageBucket: 'inpark-5a693.appspot.com',
    iosClientId: '595794346344-oa1qiraal07upiqhfcutecfbcnp3j03n.apps.googleusercontent.com',
    iosBundleId: 'com.example.inparkmanager',
  );
}
